[build]
command = """
composer install \
&& ./vendor/drush/drush/drush tome:install -y \
&& ./vendor/drush/drush/drush tome:static -l $DEPLOY_PRIME_URL
"""

# Example lines you can add before "tome:static" above if needed:
#&& LUNR_DRUSH=./vendor/bin/drush node web/modules/contrib/lunr/js/index.node.js default \
#&& ./vendor/bin/drush simple-sitemap-generate -y -l $DEPLOY_PRIME_URL \
#&& cp html/404/index.html html/404.html \

publish = "html"

[build.environment]
PHP_VERSION="7.4"
